/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QueryImport } from './routes/query'
import { Route as MapImport } from './routes/map'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as RolesIndexImport } from './routes/roles/index'
import { Route as RagIndexImport } from './routes/rag/index'
import { Route as RolesRoleInfoImport } from './routes/roles/role-info'
import { Route as RolesCreateRoleImport } from './routes/roles/create-role'
import { Route as ProductsCodeListImport } from './routes/products/code/list'
import { Route as ProductsCodeCodeDetailImport } from './routes/products/code/code-detail'

// Create/Update Routes

const QueryRoute = QueryImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRoute,
} as any)

const MapRoute = MapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const RolesIndexRoute = RolesIndexImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRoute,
} as any)

const RagIndexRoute = RagIndexImport.update({
  id: '/rag/',
  path: '/rag/',
  getParentRoute: () => rootRoute,
} as any)

const RolesRoleInfoRoute = RolesRoleInfoImport.update({
  id: '/roles/role-info',
  path: '/roles/role-info',
  getParentRoute: () => rootRoute,
} as any)

const RolesCreateRoleRoute = RolesCreateRoleImport.update({
  id: '/roles/create-role',
  path: '/roles/create-role',
  getParentRoute: () => rootRoute,
} as any)

const ProductsCodeListRoute = ProductsCodeListImport.update({
  id: '/products/code/list',
  path: '/products/code/list',
  getParentRoute: () => rootRoute,
} as any)

const ProductsCodeCodeDetailRoute = ProductsCodeCodeDetailImport.update({
  id: '/products/code/code-detail',
  path: '/products/code/code-detail',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryImport
      parentRoute: typeof rootRoute
    }
    '/roles/create-role': {
      id: '/roles/create-role'
      path: '/roles/create-role'
      fullPath: '/roles/create-role'
      preLoaderRoute: typeof RolesCreateRoleImport
      parentRoute: typeof rootRoute
    }
    '/roles/role-info': {
      id: '/roles/role-info'
      path: '/roles/role-info'
      fullPath: '/roles/role-info'
      preLoaderRoute: typeof RolesRoleInfoImport
      parentRoute: typeof rootRoute
    }
    '/rag/': {
      id: '/rag/'
      path: '/rag'
      fullPath: '/rag'
      preLoaderRoute: typeof RagIndexImport
      parentRoute: typeof rootRoute
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/code/code-detail': {
      id: '/products/code/code-detail'
      path: '/products/code/code-detail'
      fullPath: '/products/code/code-detail'
      preLoaderRoute: typeof ProductsCodeCodeDetailImport
      parentRoute: typeof rootRoute
    }
    '/products/code/list': {
      id: '/products/code/list'
      path: '/products/code/list'
      fullPath: '/products/code/list'
      preLoaderRoute: typeof ProductsCodeListImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/query': typeof QueryRoute
  '/roles/create-role': typeof RolesCreateRoleRoute
  '/roles/role-info': typeof RolesRoleInfoRoute
  '/rag': typeof RagIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/products/code/code-detail': typeof ProductsCodeCodeDetailRoute
  '/products/code/list': typeof ProductsCodeListRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/query': typeof QueryRoute
  '/roles/create-role': typeof RolesCreateRoleRoute
  '/roles/role-info': typeof RolesRoleInfoRoute
  '/rag': typeof RagIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/products/code/code-detail': typeof ProductsCodeCodeDetailRoute
  '/products/code/list': typeof ProductsCodeListRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/query': typeof QueryRoute
  '/roles/create-role': typeof RolesCreateRoleRoute
  '/roles/role-info': typeof RolesRoleInfoRoute
  '/rag/': typeof RagIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/products/code/code-detail': typeof ProductsCodeCodeDetailRoute
  '/products/code/list': typeof ProductsCodeListRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/map'
    | '/query'
    | '/roles/create-role'
    | '/roles/role-info'
    | '/rag'
    | '/roles'
    | '/users'
    | '/products/code/code-detail'
    | '/products/code/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map'
    | '/query'
    | '/roles/create-role'
    | '/roles/role-info'
    | '/rag'
    | '/roles'
    | '/users'
    | '/products/code/code-detail'
    | '/products/code/list'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/map'
    | '/query'
    | '/roles/create-role'
    | '/roles/role-info'
    | '/rag/'
    | '/roles/'
    | '/users/'
    | '/products/code/code-detail'
    | '/products/code/list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  QueryRoute: typeof QueryRoute
  RolesCreateRoleRoute: typeof RolesCreateRoleRoute
  RolesRoleInfoRoute: typeof RolesRoleInfoRoute
  RagIndexRoute: typeof RagIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ProductsCodeCodeDetailRoute: typeof ProductsCodeCodeDetailRoute
  ProductsCodeListRoute: typeof ProductsCodeListRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  QueryRoute: QueryRoute,
  RolesCreateRoleRoute: RolesCreateRoleRoute,
  RolesRoleInfoRoute: RolesRoleInfoRoute,
  RagIndexRoute: RagIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ProductsCodeCodeDetailRoute: ProductsCodeCodeDetailRoute,
  ProductsCodeListRoute: ProductsCodeListRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/login",
        "/map",
        "/query",
        "/roles/create-role",
        "/roles/role-info",
        "/rag/",
        "/roles/",
        "/users/",
        "/products/code/code-detail",
        "/products/code/list"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/map": {
      "filePath": "map.jsx"
    },
    "/query": {
      "filePath": "query.jsx"
    },
    "/roles/create-role": {
      "filePath": "roles/create-role.jsx"
    },
    "/roles/role-info": {
      "filePath": "roles/role-info.jsx"
    },
    "/rag/": {
      "filePath": "rag/index.jsx"
    },
    "/roles/": {
      "filePath": "roles/index.jsx"
    },
    "/users/": {
      "filePath": "users/index.jsx"
    },
    "/products/code/code-detail": {
      "filePath": "products/code/code-detail.jsx"
    },
    "/products/code/list": {
      "filePath": "products/code/list.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
